# Site settings
title: Aditya
subtitle: Raman
email: adityaraman96@gmail.com
altemail: adityaraman_cs004@sirmvit.edu
description: >- # this means to ignore newlines until "baseurl:"
  Entrepreneur | Backend Developer | Software Engineer | MLH Fellow |
  DevOps | Gold Microsoft Learn Student Ambassador
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
repository: ramanaditya/ramanaditya.github.io
github: [metadata]
author: Aditya
street_address: Whitefield
city: Bengaluru
state: Karnataka
zip_code: 560066
country: India
phone: (+91) 99015-61092

# Social settings
500px_url:
facebook_url: https://fb.com/adityaraman6
github_url: https://github.com/ramanaditya
gitlab_url: https://gitlab.com/ramanaditya
googleplus_url: 
instagram_url: https://instagram.com/_adityaraman
linkedin_url: https://www.linkedin.com/in/ramanaditya
pinterest_url:
slack_url:
twitter_url: https://twitter.com/_adityaraman
medium_url: https://ramanaditya.medium.com/
disqus: ramanaditya

# Build settings
markdown: kramdown
lazyimages: "enab"
sass:
  style: compressed

highlighter: rouge

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-twitter-plugin
  - jekyll-last-modified-at
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-gzip
  
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-twitter-plugin
  - jekyll-last-modified-at
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-gzip

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: page
  permalinks:
    category: '/category/:name/'

gist:
  noscript: false


paginate: 6
paginate_path: /page:num/

gzip:
  extensions:
    - '.html'
    - '.css'
    - '.js'
  replace_files: false
