# Site settings
title: Aditya
subtitle: Raman
email: adityaraman96@gmail.com
altemail: adityaraman_cs004@sirmvit.edu
description: BACK END DEVELOPER | SOFTWARE ENGINEER | MLH FELLOW | DEVOPS | MICROSOFT LEARN STUDENT AMBASSADOR | MENTOR @MLH
baseurl:  # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site
author: Aditya
street_address: Hunasamaranahalli
city: Bengaluru
state: Karnataka
zip_code: 562157
country: India
phone: (+91) 99015-61092

# Social settings
500px_url:
facebook_url: https://fb.com/adityaraman6
github_url: https://github.com/ramanaditya
gitlab_url: https://gitlab.com/ramanaditya
googleplus_url: 
instagram_url: https://instagram.com/_adityaraman
linkedin_url: https://www.linkedin.com/in/ramanaditya
pinterest_url:
slack_url:
twitter_url: https://twitter.com/_adityaraman
disqus: ramanaditya

# Build settings
markdown: kramdown
lazyimages: "enab"
sass:
  style: compressed

highlighter: rouge

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-twitter-plugin
  - jekyll-last-modified-at
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-twitter-plugin
  - jekyll-last-modified-at
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: page
  permalinks:
    category: '/category/:name/'

gist:
  noscript: false


paginate: 6
paginate_path: /page:num/

