# Site settings
title: Aditya
subtitle: Raman
email: adityaraman96@gmail.com
altemail: adityaraman_cs004@sirmvit.edu
description: Data Science Enthusiast, Former Full Stack Developer Intern
baseurl:  # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site
author: Aditya
street_address: Hunasamaranahalli
city: Bengaluru
state: Karnataka
zip_code: 562157
country: India
phone: (+91) 99015-61092

# Social settings
500px_url:
facebook_url: https://fb.com/adityaraman6
github_url: https://github.com/ramanaditya
gitlab_url: https://gitlab.com/ramanaditya
googleplus_url: 
instagram_url: https://instagram.com/_adityaraman
INSTAGRAM_USER_ID: 1603713456
INSTAGRAM_CLIENT_ID: ed06ece6ad2b40b184c0fafa994a84af
#access_token: 1603713456.1677ed0.f0991c2e6b5f49a6bcfa0bc963c19d43
linkedin_url: https://www.linkedin.com/in/ramanaditya
pinterest_url:
slack_url:
twitter_url: https://twitter.com/_adityaraman
disqus: ramanaditya

# Build settings
markdown: kramdown
lazyimages: "enab"
sass:
  style: compressed

highlighter: rouge

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-twitter-plugin
  - jekyll-last-modified-at
  
gist:
  noscript: false

permalink: /:categories/:title
paginate: 6
paginate_path: /page:num/


instafeed: true